### ISSUE TITLE
TexWorks报错

### ISSUE THREAD

**Issue by BoYangXDU** [note286/xdupgtp#2]
https://github.com/note286/xdupgtp/blob/95724e420480003bf4ea4dc0faca88488590b655/xdupgtp.tex#L122-L124

使用TexWorks编译，上述代码处报错信息为：

`Missing number, treated as zero.
<to be read again> 
                   \vskip 
l.122 \begin{pyjl}`

ps:注释上述代码后可以通过编译

**Comment by note286** [comment]
TeX Live 2022无任何问题。

**Comment by BoYangXDU** [comment]
> TeX Live 2022无任何问题。

升级版本后确实解决了
